// WARNING START OF SECTION AUTOGENERATED BY PYTHON SCRIPT
// THIS SECTION MAY BE AUTOMATICALLY CHANGED AT ANY TIME
// Autogenerated section name: EEPROM Layout Config
// File path of script: ARD/genEEPROMLAYOUT.py

#ifndef EEPROM_LAYOUT_HEADER_H_
#define EEPROM_LAYOUT_HEADER_H_

#include <stdint.h>

// EEPROM Layout Version ID 1
struct sensorBoardLayoutRev1 {
	uint32_t Layout_Rev_Number;
	uint32_t EEPROM_Layout_Compile_Time;
	uint32_t Board_Status;
	uint32_t Board_VIN_Voltage_CanID;
	uint32_t Board_VIN_Current_CanID;
	uint32_t PT0_Data_CanID;
	uint32_t PT0_Current_CanID;
	uint32_t PT0_Data_Frequency;
	uint32_t PT0_Sample_Rate;
	float PT0_Max_Output_Voltage;
	float PT0_Min_Output_Voltage;
	float PT0_Max_Pressure;
	float PT0_Min_Pressure;
	float PT0_Calibration_Polyfit_p1;
	float PT0_Calibration_Polyfit_p2;
	float PT0_Calibration_Polyfit_p3;
	float PT0_Calibration_Polyfit_p4;
	float PT0_Calibration_Polyfit_p5;
	float PT0_Calibration_Polyfit_p6;
	float PT0_Calibration_Polyfit_p7;
	float PT0_Biquad_Filter_b0;
	float PT0_Biquad_Filter_b1;
	float PT0_Biquad_Filter_b2;
	float PT0_Biquad_Filter_a1;
	float PT0_Biquad_Filter_a2;
	uint32_t PT1_Data_CanID;
	uint32_t PT1_Current_CanID;
	uint32_t PT1_Data_Frequency;
	uint32_t PT1_Sample_Rate;
	float PT1_Max_Output_Voltage;
	float PT1_Min_Output_Voltage;
	float PT1_Max_Pressure;
	float PT1_Min_Pressure;
	float PT1_Calibration_Polyfit_p1;
	float PT1_Calibration_Polyfit_p2;
	float PT1_Calibration_Polyfit_p3;
	float PT1_Calibration_Polyfit_p4;
	float PT1_Calibration_Polyfit_p5;
	float PT1_Calibration_Polyfit_p6;
	float PT1_Calibration_Polyfit_p7;
	float PT1_Biquad_Filter_b0;
	float PT1_Biquad_Filter_b1;
	float PT1_Biquad_Filter_b2;
	float PT1_Biquad_Filter_a1;
	float PT1_Biquad_Filter_a2;
	uint32_t PT2_Data_CanID;
	uint32_t PT2_Current_CanID;
	uint32_t PT2_Data_Frequency;
	uint32_t PT2_Sample_Rate;
	float PT2_Max_Output_Voltage;
	float PT2_Min_Output_Voltage;
	float PT2_Max_Pressure;
	float PT2_Min_Pressure;
	float PT2_Calibration_Polyfit_p1;
	float PT2_Calibration_Polyfit_p2;
	float PT2_Calibration_Polyfit_p3;
	float PT2_Calibration_Polyfit_p4;
	float PT2_Calibration_Polyfit_p5;
	float PT2_Calibration_Polyfit_p6;
	float PT2_Calibration_Polyfit_p7;
	float PT2_Biquad_Filter_b0;
	float PT2_Biquad_Filter_b1;
	float PT2_Biquad_Filter_b2;
	float PT2_Biquad_Filter_a1;
	float PT2_Biquad_Filter_a2;
	uint32_t HE0_Data_CanID;
	uint32_t HE0_Current_CanID;
	uint32_t HE0_Data_Frequency;
	uint32_t HE0_Sample_Rate;
	uint32_t HE1_Data_CanID;
	uint32_t HE1_Current_CanID;
	uint32_t HE1_Data_Frequency;
	uint32_t HE1_Sample_Rate;
	uint32_t HE2_Data_CanID;
	uint32_t HE2_Current_CanID;
	uint32_t HE2_Data_Frequency;
	uint32_t HE2_Sample_Rate;
	uint32_t TC0_Data_CanID;
	uint32_t TC0_Data_Frequency;
	uint32_t TC0_Sample_Rate;
	float TC0_Biquad_Filter_b0;
	float TC0_Biquad_Filter_b1;
	float TC0_Biquad_Filter_b2;
	float TC0_Biquad_Filter_a1;
	float TC0_Biquad_Filter_a2;
	uint32_t TC1_Data_CanID;
	uint32_t TC1_Data_Frequency;
	uint32_t TC1_Sample_Rate;
	float TC1_Biquad_Filter_b0;
	float TC1_Biquad_Filter_b1;
	float TC1_Biquad_Filter_b2;
	float TC1_Biquad_Filter_a1;
	float TC1_Biquad_Filter_a2;
	uint32_t RTD0_Data_CanID;
	uint32_t RTD0_Data_Frequency;
	uint32_t RTD0_Sample_Rate;
	float RTD0_Biquad_Filter_b0;
	float RTD0_Biquad_Filter_b1;
	float RTD0_Biquad_Filter_b2;
	float RTD0_Biquad_Filter_a1;
	float RTD0_Biquad_Filter_a2;
	uint32_t RTD1_Data_CanID;
	uint32_t RTD1_Data_Frequency;
	uint32_t RTD1_Sample_Rate;
	float RTD1_Biquad_Filter_b0;
	float RTD1_Biquad_Filter_b1;
	float RTD1_Biquad_Filter_b2;
	float RTD1_Biquad_Filter_a1;
	float RTD1_Biquad_Filter_a2;
	uint32_t CS0_Data_CanID;
	float CS0_Biquad_Filter_b0;
	float CS0_Biquad_Filter_b1;
	float CS0_Biquad_Filter_b2;
	float CS0_Biquad_Filter_a1;
	float CS0_Biquad_Filter_a2;
} __attribute((aligned (1))); // sensorBoardLayoutRev1

// EEPROM Layout Version ID 2
struct powerDistroBoardLayoutRev1 {
	uint32_t Board_Status;
	uint32_t Offboard_Battery_Voltage_CANID;
	uint32_t Offboard_Battery_Current_CANID;
	uint32_t Onboard_Battery_Voltage_CANID;
	uint32_t Onboard_Battery_Current_CANID;
	uint32_t Helix_Loop_CW_Voltage_CANID;
	uint32_t Helix_Loop_CW_Current_CANID;
	uint32_t Helix_Loop_CCW_Voltage_CANID;
	uint32_t Helix_Loop_CCW_Current_CANID;
} __attribute((aligned (1))); // powerDistroBoardLayoutRev1

enum layoutVersionIDs {
	SENSOR_BOARD_LAYOUT_REV_1, 	 // 1
	POWER_DISTRO_BOARD_LAYOUT_REV_1, 	 // 2
	MAX_LAYOUT_VERSION_IDS
};


#endif // EEPROM_LAYOUT_HEADER_H_

// WARNING END OF SECTION AUTOGENERATED BY PYTHON SCRIPT
// THIS SECTION MAY BE AUTOMATICALLY CHANGED AT ANY TIME
// Autogenerated section name: EEPROM Layout Config
// File path of script: ARD/genEEPROMLAYOUT.py
