#ifndef HELIX_OBC_FIRMWARE_H_
#define HELIX_OBC_FIRMWARE_H_

#include <CANIDs.h>

enum HOBC_RETURNS : uint32_t {
    HOBC_SUCCESS,
    HOBC_INVALID_ARG,
    HOBC_NOT_INIT,
    HOBC_FAILURE
};

enum CANIDS_EXTENDED : uint32_t {
    CANIDS_EXTENDED_BASE = CANIDS_MAX_CANID,
    CANIDS_EXTENDED_QUIT,
    
    CANIDS_EXTENDED_STATE_ENTER,
    CANIDS_EXTENDED_STATE_EXIT,

    CANIDS_LEAK_CHECK_HELIUM_PRESSURE_CHECK,

    CANIDS_EXTENDED_MAX
};

#endif // HELIX_OBC_FIRMWARE_H_